<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-03-05T14:15:13Z" name="Regression" finished-at="2018-03-05T14:17:36Z" duration-ms="143331">
    <groups>
    </groups>
    <test started-at="2018-03-05T14:15:13Z" name="Automation" finished-at="2018-03-05T14:17:36Z" duration-ms="143331">
      <class name="com.devOps_Test.DevOps_Selenium">
        <test-method signature="Test_DevOps_OpenActivities()[pri:0, instance:com.devOps_Test.DevOps_Selenium@40005471]" started-at="2018-03-05T19:45:13Z" name="Test_DevOps_OpenActivities" finished-at="2018-03-05T19:46:31Z" duration-ms="77577" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [True] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [True] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.devOps_Test.DevOps_Selenium.Test_DevOps_OpenActivities(DevOps_Selenium.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_DevOps_OpenActivities -->
        <test-method signature="Test_DevOps_PatientAddress()[pri:0, instance:com.devOps_Test.DevOps_Selenium@40005471]" started-at="2018-03-05T19:46:31Z" name="Test_DevOps_PatientAddress" finished-at="2018-03-05T19:47:36Z" duration-ms="65730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_DevOps_PatientAddress -->
      </class> <!-- com.devOps_Test.DevOps_Selenium -->
    </test> <!-- Automation -->
  </suite> <!-- Regression -->
</testng-results>
